### ISSUE TITLE
[Feature] Could you please tell me what's the "reddit_client_id" and the '<client-secret>'?

### ISSUE THREAD

**Issue by FVDH1127** [kriticalflare/KustomPyper#8] opened 2022-03-31 11:48 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kriticalflare** [comment] 2022-04-01 08:25
duplicate of #9

**Closed as completed by kriticalflare** 2022-04-01 08:25 UTC
Labels: enhancement
